import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, collection, query, where, getDocs } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyByXWYR1xhqWWyIaI5qfKR9RAKA0zO7LkM',authDomain:'mind-walk-class.firebaseapp.com',projectId:'mind-walk-class',storageBucket:'mind-walk-class.firebasestorage.app',messagingSenderId:'924625035793',appId:'1:924625035793:web:be4d15237db05b34c8c7b0'};
const studentApp=initializeApp(firebaseConfig);
const teacherApp=initializeApp(firebaseConfig,'teacher');
const auth=getAuth(studentApp),db=getFirestore(studentApp),teacherAuth=getAuth(teacherApp),teacherDb=getFirestore(teacherApp);
const $=s=>document.querySelector(s);
const lessons=[['나를 만나는 섬','오늘 나를 기분 좋게 만든 작은 일은 무엇인가요?'],['용기의 언덕','최근 용기를 냈던 순간을 떠올려 보세요.'],['경청의 숲','친구의 말을 잘 들었을 때 무엇을 알게 되었나요?'],['감사의 연못','오늘 고마웠던 사람과 그 이유를 적어 보세요.'],['협동의 다리','함께해서 혼자보다 잘할 수 있었던 일은?'],['감정의 바다','지금 내 마음을 날씨로 표현한다면 어떤가요?'],['선택의 갈림길','좋은 선택을 위해 내가 중요하게 생각하는 것은?'],['도전의 산','포기하고 싶었지만 조금 더 해본 경험은?'],['배려의 마을','누군가를 편안하게 해 준 행동을 떠올려 보세요.'],['꿈의 정원','내가 좋아하고 더 잘하고 싶은 일은 무엇인가요?'],['회복의 동굴','실수한 뒤 다시 시작하는 나만의 방법은?'],['약속의 광장','나와 친구를 위해 지키고 싶은 약속은?'],['관점의 전망대','다른 사람의 입장에서 보니 달라진 생각은?'],['성장의 들판','처음보다 달라진 나의 모습을 찾아보세요.'],['새출발 등대','앞으로 이어가고 싶은 마음 습관 하나는?']];
const chars=[['🌱','새싹이'],['🦊','여우'],['🐳','고래'],['🦉','부엉이'],['🐰','토끼'],['🐯','호랑이'],['🐢','거북이'],['🐙','문어']];
const points=[[10,87.6],[24,88.4],[40.8,84.5],[58.7,90.3],[83.7,83.8],[79.1,71.3],[65.6,54.8],[50.8,60.4],[13.8,69.3],[22.7,56.6],[18.9,39.7],[25.6,22.6],[46.4,28.4],[66.7,38.8],[87.2,19.8]];
const defaultSchedule=()=>lessons.map((_,i)=>{const d=new Date('2026-08-26T00:00:00');d.setDate(d.getDate()+i);return d.toISOString().slice(0,10)});
const freshState=()=>({name:'',avatar:'🌱',progress:0,steps:0,entries:[],last:'',seen:-1,schedule:defaultSchedule(),walkSessions:{},teacherOverrides:{}});
let state=freshState(),selected='🌱',walking=false,lastMotion=0,rapidSteps=0,runBlockUntil=0,runningWarningOpen=false,lastRenderedSteps=0,timerHandle=null,pressTimer=null,teacherModeActive=false,teacherClass=null,currentStudentUid=null,teacherAction='panel',pendingResetIndex=null,saveTimer=null;

function escapeHtml(value=''){return String(value).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]))}
function studentEmail(classNo,studentNo){return `student-g6-c${classNo}-n${String(studentNo).padStart(2,'0')}@mindwalk.school`}
function teacherEmail(classNo){return `teacher-class${classNo}@mindwalk.school`}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hide');setTimeout(()=>$('#toast').classList.add('hide'),2600)}
function cleanState(){const {credentials,teacherPinHash,...safe}=state;return {...safe,ownerUid:currentStudentUid,grade:6,classNo:Number(state.classNo),studentNo:Number(state.studentNo),updatedAt:new Date().toISOString()}}
function save(remote=true){localStorage.setItem('mindwalk-cache',JSON.stringify(cleanState()));if(!remote||!auth.currentUser||!currentStudentUid)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>setDoc(doc(db,'students',currentStudentUid),cleanState(),{merge:true}).catch(()=>toast('기록을 서버에 저장하지 못했습니다. 인터넷 연결을 확인해 주세요.')),250)}
async function loadCourse(classNo,firestore=db){const ref=doc(firestore,'course',`class-${classNo}`),snap=await getDoc(ref);if(snap.exists()&&Array.isArray(snap.data().schedule))return snap.data().schedule;return defaultSchedule()}
function normalize(data={}){return {...freshState(),...data,entries:Array.isArray(data.entries)?data.entries:[],walkSessions:data.walkSessions||{},teacherOverrides:data.teacherOverrides||{}}}

document.body.insertAdjacentHTML('beforeend',`
<div class="modal" id="studentAccess"><div class="dialog"><div class="eyebrow">STUDENT ACCESS</div><h2>마음걸음 시작하기</h2><p>6학년 반과 번호를 선택하고 비밀번호를 입력하세요.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><label for="loginClass">반</label><select id="loginClass"><option value="1">1반</option><option value="2">2반</option><option value="3">3반</option></select></div><div><label for="loginNumber">번호</label><select id="loginNumber">${Array.from({length:22},(_,i)=>`<option value="${i+1}">${i+1}번</option>`).join('')}</select></div></div><label for="loginPassword">비밀번호</label><input id="loginPassword" type="password" minlength="6" maxlength="30" autocomplete="current-password" placeholder="6자 이상"><button class="btn" id="studentLogin" style="width:100%;margin-top:18px">로그인</button><button class="btn secondary" id="studentCreate" style="width:100%;margin-top:8px">처음 시작하는 학생</button><button id="teacherEntry" style="display:block;margin:18px auto 0;border:0;background:transparent;color:#70756f;text-decoration:underline">교사용 입장</button></div></div>
<div class="modal hide" id="teacherAuth"><div class="dialog"><div class="eyebrow">TEACHER ACCESS</div><h2>교사용 인증</h2><p id="teacherAuthCopy">담당 반과 교사용 비밀번호를 입력하세요.</p><label for="teacherClass">담당 반</label><select id="teacherClass"><option value="1">1반 교사</option><option value="2">2반 교사</option><option value="3">3반 교사</option></select><label for="teacherPassword">비밀번호</label><input id="teacherPassword" type="password" maxlength="30" autocomplete="current-password"><div style="display:flex;gap:8px;margin-top:18px"><button class="btn secondary" id="closeTeacherAuth">취소</button><button class="btn" id="enterTeacher" style="flex:1">확인</button></div></div></div>
<div class="modal hide" id="runningWarning" role="alertdialog" aria-modal="true" aria-labelledby="runningWarningTitle"><div class="dialog" style="width:min(430px,100%);text-align:center"><div class="eyebrow">SAFETY NOTICE</div><h2 id="runningWarningTitle">뛰면 안 됩니다!</h2><p style="line-height:1.7">움직임이 너무 빠르게 감지되었어요.<br>잠시 멈춘 뒤 천천히 걸어주세요.</p><button class="btn" id="confirmRunningWarning" style="width:100%;margin-top:14px">확인</button></div></div>
<div class="modal hide" id="resetChoice"><div class="dialog" style="width:min(500px,100%)"><div class="eyebrow">RESET RECORDS</div><h2>기록 초기화</h2><p style="line-height:1.65">초기화할 범위를 선택하세요. 교사용 비밀번호 확인 후 실행됩니다.</p><button class="btn" id="resetAll" style="width:100%;margin-top:12px">모든 기록 초기화</button><div style="border-top:1px solid #d5d6cf;margin:22px 0 18px"></div><label for="resetLessonSelect">초기화할 날짜</label><select id="resetLessonSelect"></select><p class="hint">선택한 차시부터 이후 기록과 진행도가 초기화됩니다.</p><button class="btn secondary" id="resetSelected" style="width:100%;margin-top:8px">선택한 날짜부터 초기화</button><button class="btn secondary" id="closeResetChoice" style="width:100%;margin-top:8px;border:0">취소</button></div></div>
<div class="modal hide" id="passwordReset"><div class="dialog" style="width:min(470px,100%)"><div class="eyebrow">PASSWORD RESET</div><h2>학생 비밀번호 초기화</h2><p id="passwordResetStudent" style="line-height:1.65"></p><label for="newStudentPassword">새 비밀번호</label><input id="newStudentPassword" type="password" minlength="6" maxlength="30" autocomplete="new-password" placeholder="6자 이상"><label for="confirmStudentPassword">새 비밀번호 확인</label><input id="confirmStudentPassword" type="password" minlength="6" maxlength="30" autocomplete="new-password" placeholder="같은 비밀번호 다시 입력"><p class="hint">초기화하면 학생은 다음 로그인부터 새 비밀번호를 사용합니다.</p><div style="display:flex;gap:8px;margin-top:18px"><button class="btn secondary" id="closePasswordReset">취소</button><button class="btn" id="submitPasswordReset" style="flex:1">비밀번호 초기화</button></div></div></div>
<div class="modal hide" id="teacherPanel"><div class="dialog teacher-panel"><div class="teacher-toolbar"><div><div class="eyebrow">TEACHER MODE · ON</div><h2 style="margin:4px 0"><span id="teacherPanelClass"></span> 수업 관리</h2></div><div style="display:flex;gap:7px"><button class="btn secondary" id="closeTeacherPanel">관리창 닫기</button><button class="btn" id="turnOffTeacher">교사모드 끄기</button></div></div><div class="teacher-tabs"><button class="btn" id="tabEntries">학생 성찰일지</button><button class="btn secondary" id="tabSchedule">공개 날짜</button></div><div id="teacherContent"></div></div></div>`);
$('.profile').insertAdjacentHTML('beforeend','<button class="reset-entry" id="resetJournals" type="button">기록 초기화</button>');
$('.brand small').insertAdjacentHTML('beforebegin','<span class="teacher-badge hide" id="teacherBadge">- 교사용</span>');
$('#phaseCopy').insertAdjacentHTML('afterend','<button class="btn secondary teacher-preview hide" id="teacherPreview">교사 권한으로 열람하기</button>');
$('.goal').insertAdjacentHTML('beforebegin','<div class="timer-box"><small>걷기 시간</small><span class="timer" id="timer">00:00</span></div>');
$('.hint').insertAdjacentHTML('beforebegin','<button class="btn secondary admin-unlock hide" id="adminUnlock">타이머를 교사에게 보여주고 승인받기</button>');
$('#addBtn').classList.add('hide');
document.querySelectorAll('select').forEach(x=>Object.assign(x.style,{width:'100%',padding:'13px',border:'1px solid #bbbdb7',borderRadius:'3px',background:'#fff',font:'inherit'}));

chars.forEach(c=>$('#chars').insertAdjacentHTML('beforeend',`<button class="char ${c[0]===selected?'selected':''}" data-a="${c[0]}">${c[0]}<small>${c[1]}</small></button>`));
document.querySelectorAll('.char').forEach(b=>b.onclick=()=>{selected=b.dataset.a;document.querySelectorAll('.char').forEach(x=>x.classList.toggle('selected',x===b))});

const todayKey=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});
function dateOpen(i){return teacherModeActive||todayKey()>=(state.schedule[i]||'9999-12-31')}
function dateLabel(value){const d=new Date(value+'T00:00:00');return `${d.getMonth()+1}월 ${d.getDate()}일부터 가능합니다.`}
function elapsedSeconds(){const s=state.walkSessions[state.progress];if(!s)return 0;return Math.max(0,Math.floor(((s.stoppedAt||Date.now())-s.startedAt)/1000))}
function formatTime(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function refreshTimer(){const sec=elapsedSeconds();$('#timer').textContent=formatTime(sec);$('#adminUnlock').classList.toggle('hide',sec<900||state.steps>=2000||!auth.currentUser)}
function startClock(){clearInterval(timerHandle);timerHandle=setInterval(refreshTimer,1000);refreshTimer()}

function render(){const ready=state.seen===state.progress,walkDone=state.steps>=2000,open=state.progress<15&&dateOpen(state.progress);$('#topAvatar').textContent=state.avatar;$('#topName').textContent=state.name||'새 탐험가';$('#heroName').textContent=state.name||'탐험가';$('#topProgress').textContent=$('#islandCount').textContent=state.progress;$('#steps').textContent=state.steps;$('#walkFill').style.width=Math.min(100,state.steps/20)+'%';$('#teacherBadge').classList.toggle('hide',!teacherModeActive);$('#teacherPreview').classList.toggle('hide',!teacherModeActive||open||state.progress>=15);$('#addBtn').classList.toggle('hide',!teacherModeActive);$('#journalBtn').classList.toggle('hide',!walkDone&&!(state.teacherOverrides||{})[state.progress]);$('#walkBtn').disabled=!ready||walkDone||!open;$('#addBtn').disabled=!ready||walkDone;if(state.progress>=15){$('#phaseTitle').textContent='15개의 마음길 완주!';$('#phaseCopy').textContent='모든 성찰일지를 완성했어요.'}else if(!open){$('#phaseTitle').textContent=dateLabel(state.schedule[state.progress]);$('#phaseCopy').textContent='선생님이 지정한 날짜가 되면 다음 마음길을 시작할 수 있어요.'}else{$('#phaseTitle').textContent=!ready?'먼저 문구를 확인하세요':walkDone?'걸음 완료 · 기록할 시간':'2,000걸음 도전';$('#phaseCopy').textContent=!ready?'지도에서 현재 캐릭터가 있는 지점을 눌러보세요.':walkDone?'걸으며 떠오른 생각을 성찰일지에 남겨보세요.':'문구를 떠올리며 약 20분 동안 편안하게 걸어보세요.'}$('#route').innerHTML=lessons.map((l,i)=>`<button aria-label="${i+1}차시 ${l[0]}" style="--x:${points[i][0]}%;--y:${points[i][1]}%" class="stop ${i<state.progress?'done':i===state.progress?'active':'locked'}" data-i="${i}" ${i>state.progress?'disabled':''}>${i+1}<div class="marker">${i===state.progress?state.avatar:''}</div><div class="stop-name">${l[0]}</div></button>`).join('');document.querySelectorAll('.stop').forEach(b=>b.onclick=()=>showCheckpoint(+b.dataset.i));refreshTimer();}
function showCheckpoint(i){if(i<state.progress)return openJournal(i);if(!dateOpen(i))return toast(dateLabel(state.schedule[i]));$('#confirmCheckpoint').textContent='문구를 확인했어요 · 걷기 준비';$('#checkNo').textContent=i+1;$('#checkTitle').textContent=lessons[i][0];$('#checkPrompt').textContent=lessons[i][1];$('#checkpoint').classList.remove('hide')}
function fallbackEmpathy(text){const key=text.includes('친구')?'친구를 떠올리며 쓴 마음이 참 따뜻해요.':text.includes('힘')||text.includes('어려')?'어려운 마음도 솔직하게 바라본 점이 정말 용기 있어요.':'오늘의 마음을 이렇게 자세히 들여다본 것이 참 멋져요.';return `🤖 마음친구의 공감댓글\n${key} 기록 속에서 한 뼘 자란 마음이 느껴져요. 다음 걸음도 서두르지 말고, 지금처럼 나답게 이어가 봐요!`}
async function empathy(text){try{const token=await auth.currentUser?.getIdToken();if(!token)throw new Error('로그인이 필요합니다');const response=await fetch('/api/empathy',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({text,prompt:lessons[state.progress][1]})});if(!response.ok)throw new Error('공감댓글 생성 실패');const data=await response.json();return `🤖 마음친구의 공감댓글\n${data.reply}`}catch{return fallbackEmpathy(text)}}
function openJournal(i){if(i<state.progress){const e=state.entries[i];$('#lessonNo').textContent=i+1;$('#journalTitle').textContent=lessons[i][0];$('#prompt').textContent=lessons[i][1];$('#entry').value=e?.text||'';$('#entry').readOnly=true;$('#aiReply').textContent=e?.reply||'이미 완료한 성찰이에요.';$('#aiReply').classList.remove('hide');$('#submitJournal').dataset.mode='confirm';$('#submitJournal').textContent='확인';$('#journal').classList.remove('hide');return}if(state.steps<2000&&!state.teacherOverrides[i])return toast(`먼저 ${2000-state.steps}걸음을 더 걸어주세요!`);$('#lessonNo').textContent=i+1;$('#journalTitle').textContent=lessons[i][0];$('#prompt').textContent=lessons[i][1];$('#entry').value='';$('#entry').readOnly=false;$('#aiReply').classList.add('hide');$('#submitJournal').dataset.mode='write';$('#submitJournal').textContent='기록하기';$('#journal').classList.remove('hide')}

$('#confirmCheckpoint').onclick=()=>{state.seen=state.progress;save();$('#checkpoint').classList.add('hide');render();toast('문구 확인 완료. 이제 걸어볼까요?')};
$('#walkBtn').onclick=async()=>{if(!dateOpen(state.progress))return;walking=!walking;let session=state.walkSessions[state.progress];if(walking){if(!session||session.stoppedAt)state.walkSessions[state.progress]={startedAt:Date.now()};else session.stoppedAt=null;$('#walkBtn').textContent='걷는 중 · 멈추기';if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){try{await DeviceMotionEvent.requestPermission()}catch{toast('움직임 센서가 허용되지 않았습니다. 타이머로 참여할 수 있어요.')}}}else{state.walkSessions[state.progress].stoppedAt=Date.now();$('#walkBtn').textContent='걷기 계속하기'}save();startClock()};
function showRunningWarning(){runningWarningOpen=true;rapidSteps=0;runBlockUntil=Number.POSITIVE_INFINITY;if(navigator.vibrate)navigator.vibrate([120,80,120]);$('#runningWarning').classList.remove('hide');$('#confirmRunningWarning').focus()}
$('#confirmRunningWarning').onclick=()=>{runningWarningOpen=false;lastMotion=Date.now();rapidSteps=0;runBlockUntil=Date.now()+1200;$('#runningWarning').classList.add('hide')};
window.addEventListener('devicemotion',e=>{if(!walking||runningWarningOpen||state.steps>=2000)return;const a=e.accelerationIncludingGravity;if(!a)return;const now=Date.now();if(now<runBlockUntil)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2);if(mag>12&&now-lastMotion>350){const interval=lastMotion?now-lastMotion:9999;lastMotion=now;rapidSteps=interval<390?rapidSteps+1:0;if(rapidSteps>=5){showRunningWarning();return}state.steps++;if(state.steps!==lastRenderedSteps){lastRenderedSteps=state.steps;save(state.steps%100===0||state.steps===2000);render();if(state.steps===2000)toast('2,000걸음 완료! 성찰일지를 작성하세요')}}});
$('#addBtn').onclick=()=>{state.steps=Math.min(2000,state.steps+200);save();render();if(state.steps===2000)toast('교사용 테스트 걸음이 완료되었습니다')};
$('#journalBtn').onclick=()=>openJournal(state.progress);
$('#submitJournal').onclick=async()=>{if($('#submitJournal').dataset.mode==='confirm')return $('#journal').classList.add('hide');const text=$('#entry').value.trim();if(text.length<15)return toast('생각을 조금 더 자세히, 15자 이상 적어주세요');$('#submitJournal').disabled=true;$('#submitJournal').textContent='공감댓글을 작성하고 있어요…';const reply=await empathy(text);state.entries[state.progress]={text,reply,date:new Date().toISOString()};state.progress=Math.min(15,state.progress+1);state.steps=0;state.seen=-1;walking=false;save();$('#entry').readOnly=true;$('#aiReply').textContent=reply;$('#aiReply').classList.remove('hide');$('#submitJournal').dataset.mode='confirm';$('#submitJournal').textContent='확인';$('#submitJournal').disabled=false;render();toast('기록이 저장되고 다음 마음섬이 열렸어요')};

async function studentAccess(create){const classNo=Number($('#loginClass').value),studentNo=Number($('#loginNumber').value),password=$('#loginPassword').value;if(password.length<6)return toast('비밀번호를 6자 이상 입력해 주세요');const email=studentEmail(classNo,studentNo);try{const credential=create?await createUserWithEmailAndPassword(auth,email,password):await signInWithEmailAndPassword(auth,email,password);currentStudentUid=credential.user.uid;const ref=doc(db,'students',currentStudentUid),snap=await getDoc(ref);state=snap.exists()?normalize(snap.data()):normalize({classNo,studentNo});state.classNo=classNo;state.studentNo=studentNo;state.schedule=await loadCourse(classNo);selected=state.avatar;$('#studentAccess').classList.add('hide');if(!snap.exists()){$('#onboard').classList.remove('hide')}else{render();toast(`${state.name}, 다시 만나서 반가워요`)}}catch(error){const code=error.code||'';if(create&&code.includes('email-already-in-use'))toast('이미 등록된 학생입니다. 로그인 버튼을 눌러 주세요.');else if(!create&&(code.includes('invalid-credential')||code.includes('wrong-password')||code.includes('user-not-found')))toast('비밀번호가 맞지 않거나 등록되지 않은 학생입니다.');else toast('로그인하지 못했습니다. 잠시 후 다시 시도해 주세요.')}}
$('#studentLogin').onclick=()=>studentAccess(false);$('#studentCreate').onclick=()=>studentAccess(true);$('#loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')studentAccess(false)});
$('#start').onclick=()=>{const name=$('#name').value.trim();if(!name)return toast('탐험가 이름을 적어주세요');state.name=name;state.avatar=selected;save();$('#onboard').classList.add('hide');render();toast('탐험가 계정이 만들어졌어요')};

function showTeacherAuth(action='panel'){teacherAction=action;$('#teacherPassword').value='';$('#teacherAuthCopy').textContent=action==='approve'?'15분 걷기를 확인한 교사가 인증해 주세요.':action.startsWith('reset')?'기록 초기화를 승인할 교사가 인증해 주세요.':'담당 반과 교사용 비밀번호를 입력하세요.';if(state.classNo&&action!=='panel')$('#teacherClass').value=String(state.classNo);$('#teacherAuth').classList.remove('hide');setTimeout(()=>$('#teacherPassword').focus(),50)}
function resetFrom(index){state.entries=state.entries.slice(0,index);state.progress=index;state.steps=0;state.seen=-1;state.last='';state.walkSessions=Object.fromEntries(Object.entries(state.walkSessions||{}).filter(([key])=>Number(key)<index));state.teacherOverrides=Object.fromEntries(Object.entries(state.teacherOverrides||{}).filter(([key])=>Number(key)<index));walking=false;lastRenderedSteps=0;save();render()}
async function leaveTeacherMode(message='교사모드가 자동으로 꺼졌습니다'){teacherModeActive=false;teacherClass=null;await signOut(teacherAuth).catch(()=>{});$('#teacherPanel').classList.add('hide');render();if(message)toast(message)}
async function authenticateTeacher(){const classNo=Number($('#teacherClass').value),password=$('#teacherPassword').value;if(!password)return toast('교사용 비밀번호를 입력해 주세요');try{await signInWithEmailAndPassword(teacherAuth,teacherEmail(classNo),password);if(teacherAction!=='panel'&&Number(state.classNo)!==classNo){await signOut(teacherAuth);return toast('이 학생의 담당 반 교사만 승인할 수 있습니다.')}teacherClass=classNo;$('#teacherAuth').classList.add('hide');if(teacherAction==='approve'){state.teacherOverrides[state.progress]=true;save();await signOut(teacherAuth);openJournal(state.progress);toast('교사 확인이 완료되었습니다')}else if(teacherAction==='resetAll'){let changed=false;if(confirm('이 학생의 모든 마음일지와 진행도를 초기화할까요? 삭제한 기록은 복구할 수 없습니다.')){resetFrom(0);changed=true}await leaveTeacherMode(changed?'모든 기록이 초기화되고 교사모드가 꺼졌습니다':'교사모드가 꺼졌습니다')}else if(teacherAction==='resetSelected'){const index=pendingResetIndex;let changed=false;if(Number.isInteger(index)&&confirm(`${index+1}차시부터 이후 기록과 진행도를 초기화할까요? 삭제한 기록은 복구할 수 없습니다.`)){resetFrom(index);changed=true}pendingResetIndex=null;await leaveTeacherMode(changed?`${index+1}차시부터 초기화되고 교사모드가 꺼졌습니다`:'교사모드가 꺼졌습니다')}else{teacherModeActive=true;$('#teacherPanelClass').textContent=`6학년 ${classNo}반`;$('#teacherPanel').classList.remove('hide');$('#studentAccess').classList.add('hide');renderEntries();render()}}catch{toast('교사용 비밀번호가 맞지 않습니다.')}}
function openResetChoice(){const completed=state.entries.map((entry,index)=>entry?{entry,index}:null).filter(Boolean);$('#resetLessonSelect').innerHTML=completed.length?completed.map(({entry,index})=>`<option value="${index}">${index+1}차시 · ${escapeHtml(lessons[index][0])} · ${new Date(entry.date).toLocaleDateString('ko-KR')}</option>`).join(''):'<option value="">완료한 성찰일지가 없습니다</option>';$('#resetSelected').disabled=!completed.length;$('#resetChoice').classList.remove('hide')}
$('#teacherEntry').onclick=()=>showTeacherAuth('panel');$('#closeTeacherAuth').onclick=()=>$('#teacherAuth').classList.add('hide');$('#enterTeacher').onclick=authenticateTeacher;$('#adminUnlock').onclick=()=>showTeacherAuth('approve');$('#resetJournals').onclick=openResetChoice;$('#closeResetChoice').onclick=()=>$('#resetChoice').classList.add('hide');$('#resetAll').onclick=()=>{$('#resetChoice').classList.add('hide');showTeacherAuth('resetAll')};$('#resetSelected').onclick=()=>{pendingResetIndex=Number($('#resetLessonSelect').value);$('#resetChoice').classList.add('hide');showTeacherAuth('resetSelected')};
const brand=$('.brand');['pointerdown','touchstart'].forEach(event=>brand.addEventListener(event,()=>{clearTimeout(pressTimer);pressTimer=setTimeout(()=>showTeacherAuth('panel'),5000)}));['pointerup','pointercancel','pointerleave','touchend'].forEach(event=>brand.addEventListener(event,()=>clearTimeout(pressTimer)));
$('#closeTeacherPanel').onclick=()=>$('#teacherPanel').classList.add('hide');
$('#turnOffTeacher').onclick=()=>leaveTeacherMode('교사모드가 꺼졌습니다');
$('#teacherBadge').onclick=()=>{if(teacherModeActive){$('#teacherPanel').classList.remove('hide');renderEntries()}};
$('#teacherPreview').onclick=()=>{const i=state.progress;$('#checkNo').textContent=i+1;$('#checkTitle').textContent=lessons[i][0];$('#checkPrompt').textContent=lessons[i][1];$('#confirmCheckpoint').textContent='열람 마치기';$('#checkpoint').classList.remove('hide')};
const normalConfirm=$('#confirmCheckpoint').onclick;$('#confirmCheckpoint').onclick=()=>{if($('#confirmCheckpoint').textContent==='열람 마치기')return $('#checkpoint').classList.add('hide');normalConfirm()};

let passwordResetTarget=null;
function openPasswordReset(uid,classNo,studentNo,name){passwordResetTarget={uid,classNo,studentNo,name};$('#passwordResetStudent').textContent=`6학년 ${classNo}반 ${studentNo}번 · ${name||'이름 미설정'} 학생의 새 비밀번호를 정합니다.`;$('#newStudentPassword').value='';$('#confirmStudentPassword').value='';$('#passwordReset').classList.remove('hide');setTimeout(()=>$('#newStudentPassword').focus(),50)}
$('#closePasswordReset').onclick=()=>{$('#passwordReset').classList.add('hide');passwordResetTarget=null};
$('#submitPasswordReset').onclick=async()=>{const password=$('#newStudentPassword').value,confirmPassword=$('#confirmStudentPassword').value;if(!passwordResetTarget)return;if(password.length<6)return toast('새 비밀번호를 6자 이상 입력해 주세요');if(password!==confirmPassword)return toast('새 비밀번호가 서로 다릅니다');const button=$('#submitPasswordReset');button.disabled=true;button.textContent='초기화하는 중…';try{const token=await teacherAuth.currentUser?.getIdToken();if(!token)throw new Error('교사 인증이 만료되었습니다');const response=await fetch('/api/reset-student-password',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({studentUid:passwordResetTarget.uid,newPassword:password})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'비밀번호를 초기화하지 못했습니다');$('#passwordReset').classList.add('hide');passwordResetTarget=null;toast('학생 비밀번호가 초기화되었습니다')}catch(error){toast(error.message||'비밀번호를 초기화하지 못했습니다')}finally{button.disabled=false;button.textContent='비밀번호 초기화'}};
async function renderEntries(){if(!teacherClass)return;$('#teacherContent').innerHTML='<div class="empty">학생 기록을 불러오는 중입니다.</div>';try{const snap=await getDocs(query(collection(teacherDb,'students'),where('classNo','==',teacherClass)));const students=snap.docs.map(d=>({uid:d.id,...d.data()})).sort((a,b)=>(a.studentNo||0)-(b.studentNo||0));$('#teacherContent').innerHTML=students.length?students.map(s=>`<section class="entry-card" style="margin-top:12px"><header><strong>6학년 ${s.classNo}반 ${s.studentNo}번 · ${escapeHtml(s.name||'이름 미설정')} ${escapeHtml(s.avatar||'')}</strong><span>${s.progress||0}/15 완료</span></header><button class="btn secondary student-password-reset" style="padding:7px 10px;margin:0 0 10px" data-uid="${escapeHtml(s.uid)}" data-class="${s.classNo}" data-number="${s.studentNo}" data-name="${escapeHtml(s.name||'')}">비밀번호 초기화</button>${(s.entries||[]).map((e,i)=>e?`<details style="padding:8px 0;border-top:1px solid #e2e3dd"><summary>${i+1}차시 · ${escapeHtml(lessons[i][0])} · ${new Date(e.date).toLocaleDateString('ko-KR')}</summary><p style="margin-top:10px">${escapeHtml(e.text)}</p></details>`:'').join('')||'<p style="color:#777">아직 작성한 성찰일지가 없습니다.</p>'}</section>`).join(''):'<div class="empty">이 반에 등록된 학생이 없습니다.</div>';document.querySelectorAll('.student-password-reset').forEach(button=>button.onclick=()=>openPasswordReset(button.dataset.uid,Number(button.dataset.class),Number(button.dataset.number),button.dataset.name));$('#tabEntries').className='btn';$('#tabSchedule').className='btn secondary'}catch{$('#teacherContent').innerHTML='<div class="empty">학생 기록을 불러오지 못했습니다. Firestore 규칙을 확인해 주세요.</div>'}}
async function renderSchedule(){const schedule=await loadCourse(teacherClass,teacherDb);$('#teacherContent').innerHTML=`<div class="schedule-list">${lessons.map((l,i)=>`<label class="schedule-row"><b>${i+1}차시</b><span><strong style="display:block;margin-bottom:5px">${escapeHtml(l[0])}</strong><small style="display:block;color:#666d66;line-height:1.5">${escapeHtml(l[1])}</small></span><input type="date" aria-label="${i+1}차시 공개 날짜" data-date="${i}" value="${schedule[i]}"></label>`).join('')}</div>`;document.querySelectorAll('[data-date]').forEach(input=>input.onchange=async()=>{schedule[Number(input.dataset.date)]=input.value;await setDoc(doc(teacherDb,'course',`class-${teacherClass}`),{classNo:teacherClass,schedule,updatedAt:new Date().toISOString()},{merge:true});if(Number(state.classNo)===teacherClass){state.schedule=schedule;save();render()}toast('공개 날짜가 저장되었습니다')});$('#tabEntries').className='btn secondary';$('#tabSchedule').className='btn'}
$('#tabEntries').onclick=renderEntries;$('#tabSchedule').onclick=renderSchedule;

await signOut(auth).catch(()=>{});await signOut(teacherAuth).catch(()=>{});state=freshState();render();startClock();

