import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js';
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js';
import { getFirestore, doc, getDoc, setDoc, collection, query, where, getDocs } from 'https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyByXWYR1xhqWWyIaI5qfKR9RAKA0zO7LkM',authDomain:'mind-walk-class.firebaseapp.com',projectId:'mind-walk-class',storageBucket:'mind-walk-class.firebasestorage.app',messagingSenderId:'924625035793',appId:'1:924625035793:web:be4d15237db05b34c8c7b0'};
const studentApp=initializeApp(firebaseConfig);
const teacherApp=initializeApp(firebaseConfig,'teacher');
const auth=getAuth(studentApp),db=getFirestore(studentApp),teacherAuth=getAuth(teacherApp),teacherDb=getFirestore(teacherApp);
const $=s=>document.querySelector(s);
const lessons=[['?섎? 留뚮굹????,'?ㅻ뒛 ?섎? 湲곕텇 醫뗪쾶 留뚮뱺 ?묒? ?쇱? 臾댁뾿?멸???'],['?⑷린???몃뜒','理쒓렐 ?⑷린瑜??덈뜕 ?쒓컙???좎삱??蹂댁꽭??'],['寃쎌껌????,'移쒓뎄??留먯쓣 ???ㅼ뿀????臾댁뾿???뚭쾶 ?섏뿀?섏슂?'],['媛먯궗???곕せ','?ㅻ뒛 怨좊쭏?좊뜕 ?щ엺怨?洹??댁쑀瑜??곸뼱 蹂댁꽭??'],['?묐룞???ㅻ━','?④퍡?댁꽌 ?쇱옄蹂대떎 ?섑븷 ???덉뿀???쇱??'],['媛먯젙??諛붾떎','吏湲???留덉쓬???좎뵪濡??쒗쁽?쒕떎硫??대뼡媛??'],['?좏깮??媛덈┝湲?,'醫뗭? ?좏깮???꾪빐 ?닿? 以묒슂?섍쾶 ?앷컖?섎뒗 寃껋??'],['?꾩쟾????,'?ш린?섍퀬 ?띠뿀吏留?議곌툑 ???대낯 寃쏀뿕??'],['諛곕젮??留덉쓣','?꾧뎔媛瑜??몄븞?섍쾶 ??以 ?됰룞???좎삱??蹂댁꽭??'],['轅덉쓽 ?뺤썝','?닿? 醫뗭븘?섍퀬 ???섑븯怨??띠? ?쇱? 臾댁뾿?멸???'],['?뚮났???숆뎬','?ㅼ닔?????ㅼ떆 ?쒖옉?섎뒗 ?섎쭔??諛⑸쾿??'],['?쎌냽??愿묒옣','?섏? 移쒓뎄瑜??꾪빐 吏?ㅺ퀬 ?띠? ?쎌냽??'],['愿?먯쓽 ?꾨쭩?','?ㅻⅨ ?щ엺???낆옣?먯꽌 蹂대땲 ?щ씪吏??앷컖??'],['?깆옣???ㅽ뙋','泥섏쓬蹂대떎 ?щ씪吏??섏쓽 紐⑥뒿??李얠븘蹂댁꽭??'],['?덉텧諛??깅?','?욎쑝濡??댁뼱媛怨??띠? 留덉쓬 ?듦? ?섎굹??']];
const chars=[['?뙮','?덉떦??],['?쫲','?ъ슦'],['?맫','怨좊옒'],['?쫱','遺?됱씠'],['?맧','?좊겮'],['?맦','?몃옉??],['?맊','嫄곕턿??],['?릻','臾몄뼱']];
const points=[[10,87.6],[24,88.4],[40.8,84.5],[58.7,90.3],[83.7,83.8],[79.1,71.3],[65.6,54.8],[50.8,60.4],[13.8,69.3],[22.7,56.6],[18.9,39.7],[25.6,22.6],[46.4,28.4],[66.7,38.8],[87.2,19.8]];
const defaultSchedule=()=>lessons.map((_,i)=>{const d=new Date('2026-08-26T00:00:00');d.setDate(d.getDate()+i);return d.toISOString().slice(0,10)});
const freshState=()=>({name:'',avatar:'?뙮',progress:0,steps:0,entries:[],last:'',seen:-1,schedule:defaultSchedule(),walkSessions:{},teacherOverrides:{}});
let state=freshState(),selected='?뙮',walking=false,lastMotion=0,rapidSteps=0,runBlockUntil=0,runningWarningOpen=false,lastRenderedSteps=0,timerHandle=null,pressTimer=null,teacherModeActive=false,teacherClass=null,currentStudentUid=null,teacherAction='panel',pendingResetIndex=null,saveTimer=null;

function escapeHtml(value=''){return String(value).replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c]))}
function studentEmail(classNo,studentNo){return `student-g6-c${classNo}-n${String(studentNo).padStart(2,'0')}@mindwalk.school`}
function teacherEmail(classNo){return `teacher-class${classNo}@mindwalk.school`}
function toast(text){$('#toast').textContent=text;$('#toast').classList.remove('hide');setTimeout(()=>$('#toast').classList.add('hide'),2600)}
function cleanState(){const {credentials,teacherPinHash,...safe}=state;return {...safe,ownerUid:currentStudentUid,grade:6,classNo:Number(state.classNo),studentNo:Number(state.studentNo),updatedAt:new Date().toISOString()}}
function save(remote=true){localStorage.setItem('mindwalk-cache',JSON.stringify(cleanState()));if(!remote||!auth.currentUser||!currentStudentUid)return;clearTimeout(saveTimer);saveTimer=setTimeout(()=>setDoc(doc(db,'students',currentStudentUid),cleanState(),{merge:true}).catch(()=>toast('湲곕줉???쒕쾭????ν븯吏 紐삵뻽?듬땲?? ?명꽣???곌껐???뺤씤??二쇱꽭??')),250)}
async function loadCourse(classNo,firestore=db){const ref=doc(firestore,'course',`class-${classNo}`),snap=await getDoc(ref);if(snap.exists()&&Array.isArray(snap.data().schedule))return snap.data().schedule;return defaultSchedule()}
function normalize(data={}){return {...freshState(),...data,entries:Array.isArray(data.entries)?data.entries:[],walkSessions:data.walkSessions||{},teacherOverrides:data.teacherOverrides||{}}}

document.body.insertAdjacentHTML('beforeend',`
<div class="modal" id="studentAccess"><div class="dialog"><div class="eyebrow">STUDENT ACCESS</div><h2>留덉쓬嫄몄쓬 ?쒖옉?섍린</h2><p>6?숇뀈 諛섍낵 踰덊샇瑜??좏깮?섍퀬 鍮꾨?踰덊샇瑜??낅젰?섏꽭??</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><div><label for="loginClass">諛?/label><select id="loginClass"><option value="1">1諛?/option><option value="2">2諛?/option><option value="3">3諛?/option></select></div><div><label for="loginNumber">踰덊샇</label><select id="loginNumber">${Array.from({length:22},(_,i)=>`<option value="${i+1}">${i+1}踰?/option>`).join('')}</select></div></div><label for="loginPassword">鍮꾨?踰덊샇</label><input id="loginPassword" type="password" minlength="6" maxlength="30" autocomplete="current-password" placeholder="6???댁긽"><button class="btn" id="studentLogin" style="width:100%;margin-top:18px">濡쒓렇??/button><button class="btn secondary" id="studentCreate" style="width:100%;margin-top:8px">泥섏쓬 ?쒖옉?섎뒗 ?숈깮</button><button id="teacherEntry" style="display:block;margin:18px auto 0;border:0;background:transparent;color:#70756f;text-decoration:underline">援먯궗???낆옣</button></div></div>
<div class="modal hide" id="teacherAuth"><div class="dialog"><div class="eyebrow">TEACHER ACCESS</div><h2>援먯궗???몄쬆</h2><p id="teacherAuthCopy">?대떦 諛섍낵 援먯궗??鍮꾨?踰덊샇瑜??낅젰?섏꽭??</p><label for="teacherClass">?대떦 諛?/label><select id="teacherClass"><option value="1">1諛?援먯궗</option><option value="2">2諛?援먯궗</option><option value="3">3諛?援먯궗</option></select><label for="teacherPassword">鍮꾨?踰덊샇</label><input id="teacherPassword" type="password" maxlength="30" autocomplete="current-password"><div style="display:flex;gap:8px;margin-top:18px"><button class="btn secondary" id="closeTeacherAuth">痍⑥냼</button><button class="btn" id="enterTeacher" style="flex:1">?뺤씤</button></div></div></div>
<div class="modal hide" id="runningWarning" role="alertdialog" aria-modal="true" aria-labelledby="runningWarningTitle"><div class="dialog" style="width:min(430px,100%);text-align:center"><div class="eyebrow">SAFETY NOTICE</div><h2 id="runningWarningTitle">?곕㈃ ???⑸땲??</h2><p style="line-height:1.7">?吏곸엫???덈Т 鍮좊Ⅴ寃?媛먯??섏뿀?댁슂.<br>?좎떆 硫덉텣 ??泥쒖쿇??嫄몄뼱二쇱꽭??</p><button class="btn" id="confirmRunningWarning" style="width:100%;margin-top:14px">?뺤씤</button></div></div>
<div class="modal hide" id="resetChoice"><div class="dialog" style="width:min(500px,100%)"><div class="eyebrow">RESET RECORDS</div><h2>湲곕줉 珥덇린??/h2><p style="line-height:1.65">珥덇린?뷀븷 踰붿쐞瑜??좏깮?섏꽭?? 援먯궗??鍮꾨?踰덊샇 ?뺤씤 ???ㅽ뻾?⑸땲??</p><button class="btn" id="resetAll" style="width:100%;margin-top:12px">紐⑤뱺 湲곕줉 珥덇린??/button><div style="border-top:1px solid #d5d6cf;margin:22px 0 18px"></div><label for="resetLessonSelect">珥덇린?뷀븷 ?좎쭨</label><select id="resetLessonSelect"></select><p class="hint">?좏깮??李⑥떆遺???댄썑 湲곕줉怨?吏꾪뻾?꾧? 珥덇린?붾맗?덈떎.</p><button class="btn secondary" id="resetSelected" style="width:100%;margin-top:8px">?좏깮???좎쭨遺??珥덇린??/button><button class="btn secondary" id="closeResetChoice" style="width:100%;margin-top:8px;border:0">痍⑥냼</button></div></div>
<div class="modal hide" id="passwordReset"><div class="dialog" style="width:min(470px,100%)"><div class="eyebrow">PASSWORD RESET</div><h2>?숈깮 鍮꾨?踰덊샇 珥덇린??/h2><p id="passwordResetStudent" style="line-height:1.65"></p><label for="newStudentPassword">??鍮꾨?踰덊샇</label><input id="newStudentPassword" type="password" minlength="6" maxlength="30" autocomplete="new-password" placeholder="6???댁긽"><label for="confirmStudentPassword">??鍮꾨?踰덊샇 ?뺤씤</label><input id="confirmStudentPassword" type="password" minlength="6" maxlength="30" autocomplete="new-password" placeholder="媛숈? 鍮꾨?踰덊샇 ?ㅼ떆 ?낅젰"><p class="hint">珥덇린?뷀븯硫??숈깮? ?ㅼ쓬 濡쒓렇?몃?????鍮꾨?踰덊샇瑜??ъ슜?⑸땲??</p><div style="display:flex;gap:8px;margin-top:18px"><button class="btn secondary" id="closePasswordReset">痍⑥냼</button><button class="btn" id="submitPasswordReset" style="flex:1">鍮꾨?踰덊샇 珥덇린??/button></div></div></div>
<div class="modal hide" id="teacherPanel"><div class="dialog teacher-panel"><div class="teacher-toolbar"><div><div class="eyebrow">TEACHER MODE 쨌 ON</div><h2 style="margin:4px 0"><span id="teacherPanelClass"></span> ?섏뾽 愿由?/h2></div><div style="display:flex;gap:7px"><button class="btn secondary" id="closeTeacherPanel">愿由ъ갹 ?リ린</button><button class="btn" id="turnOffTeacher">援먯궗紐⑤뱶 ?꾧린</button></div></div><div class="teacher-tabs"><button class="btn" id="tabEntries">?숈깮 ?깆같?쇱?</button><button class="btn secondary" id="tabSchedule">怨듦컻 ?좎쭨</button></div><div id="teacherContent"></div></div></div>`);
$('.profile').insertAdjacentHTML('beforeend','<button class="reset-entry" id="resetJournals" type="button">湲곕줉 珥덇린??/button>');
$('.brand small').insertAdjacentHTML('beforebegin','<span class="teacher-badge hide" id="teacherBadge">- 援먯궗??/span>');
$('#phaseCopy').insertAdjacentHTML('afterend','<button class="btn secondary teacher-preview hide" id="teacherPreview">援먯궗 沅뚰븳?쇰줈 ?대엺?섍린</button>');
$('.goal').insertAdjacentHTML('beforebegin','<div class="timer-box"><small>嫄룰린 ?쒓컙</small><span class="timer" id="timer">00:00</span></div>');
$('.hint').insertAdjacentHTML('beforebegin','<button class="btn secondary admin-unlock hide" id="adminUnlock">??대㉧瑜?援먯궗?먭쾶 蹂댁뿬二쇨퀬 ?뱀씤諛쏄린</button>');
$('#addBtn').classList.add('hide');
document.querySelectorAll('select').forEach(x=>Object.assign(x.style,{width:'100%',padding:'13px',border:'1px solid #bbbdb7',borderRadius:'3px',background:'#fff',font:'inherit'}));

chars.forEach(c=>$('#chars').insertAdjacentHTML('beforeend',`<button class="char ${c[0]===selected?'selected':''}" data-a="${c[0]}">${c[0]}<small>${c[1]}</small></button>`));
document.querySelectorAll('.char').forEach(b=>b.onclick=()=>{selected=b.dataset.a;document.querySelectorAll('.char').forEach(x=>x.classList.toggle('selected',x===b))});

const todayKey=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Seoul'});
function dateOpen(i){return teacherModeActive||todayKey()>=(state.schedule[i]||'9999-12-31')}
function dateLabel(value){const d=new Date(value+'T00:00:00');return `${d.getMonth()+1}??${d.getDate()}?쇰???媛?ν빀?덈떎.`}
function elapsedSeconds(){const s=state.walkSessions[state.progress];if(!s)return 0;return Math.max(0,Math.floor(((s.stoppedAt||Date.now())-s.startedAt)/1000))}
function formatTime(sec){return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function refreshTimer(){const sec=elapsedSeconds();$('#timer').textContent=formatTime(sec);$('#adminUnlock').classList.toggle('hide',sec<900||state.steps>=2000||!auth.currentUser)}
function startClock(){clearInterval(timerHandle);timerHandle=setInterval(refreshTimer,1000);refreshTimer()}

function render(){const ready=state.seen===state.progress,walkDone=state.steps>=2000,open=state.progress<15&&dateOpen(state.progress);$('#topAvatar').textContent=state.avatar;$('#topName').textContent=state.name||'???먰뿕媛';$('#heroName').textContent=state.name||'?먰뿕媛';$('#topProgress').textContent=$('#islandCount').textContent=state.progress;$('#steps').textContent=state.steps;$('#walkFill').style.width=Math.min(100,state.steps/20)+'%';$('#teacherBadge').classList.toggle('hide',!teacherModeActive);$('#teacherPreview').classList.toggle('hide',!teacherModeActive||open||state.progress>=15);$('#addBtn').classList.toggle('hide',!teacherModeActive);$('#journalBtn').classList.toggle('hide',!walkDone&&!(state.teacherOverrides||{})[state.progress]);$('#walkBtn').disabled=!ready||walkDone||!open;$('#addBtn').disabled=!ready||walkDone;if(state.progress>=15){$('#phaseTitle').textContent='15媛쒖쓽 留덉쓬湲??꾩＜!';$('#phaseCopy').textContent='紐⑤뱺 ?깆같?쇱?瑜??꾩꽦?덉뼱??'}else if(!open){$('#phaseTitle').textContent=dateLabel(state.schedule[state.progress]);$('#phaseCopy').textContent='?좎깮?섏씠 吏?뺥븳 ?좎쭨媛 ?섎㈃ ?ㅼ쓬 留덉쓬湲몄쓣 ?쒖옉?????덉뼱??'}else{$('#phaseTitle').textContent=!ready?'癒쇱? 臾멸뎄瑜??뺤씤?섏꽭??:walkDone?'嫄몄쓬 ?꾨즺 쨌 湲곕줉???쒓컙':'2,000嫄몄쓬 ?꾩쟾';$('#phaseCopy').textContent=!ready?'吏?꾩뿉???꾩옱 罹먮┃?곌? ?덈뒗 吏?먯쓣 ?뚮윭蹂댁꽭??':walkDone?'嫄몄쑝硫??좎삤瑜??앷컖???깆같?쇱????④꺼蹂댁꽭??':'臾멸뎄瑜??좎삱由щŉ ??20遺??숈븞 ?몄븞?섍쾶 嫄몄뼱蹂댁꽭??'}$('#route').innerHTML=lessons.map((l,i)=>`<button aria-label="${i+1}李⑥떆 ${l[0]}" style="--x:${points[i][0]}%;--y:${points[i][1]}%" class="stop ${i<state.progress?'done':i===state.progress?'active':'locked'}" data-i="${i}" ${i>state.progress?'disabled':''}>${i+1}<div class="marker">${i===state.progress?state.avatar:''}</div><div class="stop-name">${l[0]}</div></button>`).join('');document.querySelectorAll('.stop').forEach(b=>b.onclick=()=>showCheckpoint(+b.dataset.i));refreshTimer();}
function showCheckpoint(i){if(i<state.progress)return openJournal(i);if(!dateOpen(i))return toast(dateLabel(state.schedule[i]));$('#confirmCheckpoint').textContent='臾멸뎄瑜??뺤씤?덉뼱??쨌 嫄룰린 以鍮?;$('#checkNo').textContent=i+1;$('#checkTitle').textContent=lessons[i][0];$('#checkPrompt').textContent=lessons[i][1];$('#checkpoint').classList.remove('hide')}
function fallbackEmpathy(text){const key=text.includes('移쒓뎄')?'移쒓뎄瑜??좎삱由щŉ ??留덉쓬??李??곕쑜?댁슂.':text.includes('??)||text.includes('?대젮')?'?대젮??留덉쓬???붿쭅?섍쾶 諛붾씪蹂??먯씠 ?뺣쭚 ?⑷린 ?덉뼱??':'?ㅻ뒛??留덉쓬???대젃寃??먯꽭???ㅼ뿬?ㅻ낯 寃껋씠 李?硫뗭졇??';return `?쨼 留덉쓬移쒓뎄??怨듦컧?볤?\n${key} 湲곕줉 ?띿뿉????堉??먮? 留덉쓬???먭뺨?몄슂. ?ㅼ쓬 嫄몄쓬???쒕몢瑜댁? 留먭퀬, 吏湲덉쿂???섎떟寃??댁뼱媛 遊먯슂!`}
async function empathy(text){try{const token=await auth.currentUser?.getIdToken();if(!token)throw new Error('濡쒓렇?몄씠 ?꾩슂?⑸땲??);const response=await fetch('/api/empathy',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({text,prompt:lessons[state.progress][1]})});if(!response.ok)throw new Error('怨듦컧?볤? ?앹꽦 ?ㅽ뙣');const data=await response.json();return `?쨼 留덉쓬移쒓뎄??怨듦컧?볤?\n${data.reply}`}catch{return fallbackEmpathy(text)}}
function openJournal(i){if(i<state.progress){const e=state.entries[i];$('#lessonNo').textContent=i+1;$('#journalTitle').textContent=lessons[i][0];$('#prompt').textContent=lessons[i][1];$('#entry').value=e?.text||'';$('#entry').readOnly=true;$('#aiReply').textContent=e?.reply||'?대? ?꾨즺???깆같?댁뿉??';$('#aiReply').classList.remove('hide');$('#submitJournal').dataset.mode='confirm';$('#submitJournal').textContent='?뺤씤';$('#journal').classList.remove('hide');return}if(state.steps<2000&&!state.teacherOverrides[i])return toast(`癒쇱? ${2000-state.steps}嫄몄쓬????嫄몄뼱二쇱꽭??`);$('#lessonNo').textContent=i+1;$('#journalTitle').textContent=lessons[i][0];$('#prompt').textContent=lessons[i][1];$('#entry').value='';$('#entry').readOnly=false;$('#aiReply').classList.add('hide');$('#submitJournal').dataset.mode='write';$('#submitJournal').textContent='湲곕줉?섍린';$('#journal').classList.remove('hide')}

$('#confirmCheckpoint').onclick=()=>{state.seen=state.progress;save();$('#checkpoint').classList.add('hide');render();toast('臾멸뎄 ?뺤씤 ?꾨즺. ?댁젣 嫄몄뼱蹂쇨퉴??')};
$('#walkBtn').onclick=async()=>{if(!dateOpen(state.progress))return;walking=!walking;let session=state.walkSessions[state.progress];if(walking){if(!session||session.stoppedAt)state.walkSessions[state.progress]={startedAt:Date.now()};else session.stoppedAt=null;$('#walkBtn').textContent='嫄룸뒗 以?쨌 硫덉텛湲?;if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){try{await DeviceMotionEvent.requestPermission()}catch{toast('?吏곸엫 ?쇱꽌媛 ?덉슜?섏? ?딆븯?듬땲?? ??대㉧濡?李몄뿬?????덉뼱??')}}}else{state.walkSessions[state.progress].stoppedAt=Date.now();$('#walkBtn').textContent='嫄룰린 怨꾩냽?섍린'}save();startClock()};
function showRunningWarning(){runningWarningOpen=true;rapidSteps=0;runBlockUntil=Number.POSITIVE_INFINITY;if(navigator.vibrate)navigator.vibrate([120,80,120]);$('#runningWarning').classList.remove('hide');$('#confirmRunningWarning').focus()}
$('#confirmRunningWarning').onclick=()=>{runningWarningOpen=false;lastMotion=Date.now();rapidSteps=0;runBlockUntil=Date.now()+1200;$('#runningWarning').classList.add('hide')};
window.addEventListener('devicemotion',e=>{if(!walking||runningWarningOpen||state.steps>=2000)return;const a=e.accelerationIncludingGravity;if(!a)return;const now=Date.now();if(now<runBlockUntil)return;const mag=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2);if(mag>12&&now-lastMotion>350){const interval=lastMotion?now-lastMotion:9999;lastMotion=now;rapidSteps=interval<390?rapidSteps+1:0;if(rapidSteps>=5){showRunningWarning();return}state.steps++;if(state.steps!==lastRenderedSteps){lastRenderedSteps=state.steps;save(state.steps%100===0||state.steps===2000);render();if(state.steps===2000)toast('2,000嫄몄쓬 ?꾨즺! ?깆같?쇱?瑜??묒꽦?섏꽭??)}}});
$('#addBtn').onclick=()=>{state.steps=Math.min(2000,state.steps+200);save();render();if(state.steps===2000)toast('援먯궗???뚯뒪??嫄몄쓬???꾨즺?섏뿀?듬땲??)};
$('#journalBtn').onclick=()=>openJournal(state.progress);
$('#submitJournal').onclick=async()=>{if($('#submitJournal').dataset.mode==='confirm')return $('#journal').classList.add('hide');const text=$('#entry').value.trim();if(text.length<15)return toast('?앷컖??議곌툑 ???먯꽭?? 15???댁긽 ?곸뼱二쇱꽭??);$('#submitJournal').disabled=true;$('#submitJournal').textContent='怨듦컧?볤????묒꽦?섍퀬 ?덉뼱?붴?;const reply=await empathy(text);state.entries[state.progress]={text,reply,date:new Date().toISOString()};state.progress=Math.min(15,state.progress+1);state.steps=0;state.seen=-1;walking=false;save();$('#entry').readOnly=true;$('#aiReply').textContent=reply;$('#aiReply').classList.remove('hide');$('#submitJournal').dataset.mode='confirm';$('#submitJournal').textContent='?뺤씤';$('#submitJournal').disabled=false;render();toast('湲곕줉????λ릺怨??ㅼ쓬 留덉쓬?ъ씠 ?대졇?댁슂')};

async function studentAccess(create){const classNo=Number($('#loginClass').value),studentNo=Number($('#loginNumber').value),password=$('#loginPassword').value;if(password.length<6)return toast('鍮꾨?踰덊샇瑜?6???댁긽 ?낅젰??二쇱꽭??);const email=studentEmail(classNo,studentNo);try{const credential=create?await createUserWithEmailAndPassword(auth,email,password):await signInWithEmailAndPassword(auth,email,password);currentStudentUid=credential.user.uid;const ref=doc(db,'students',currentStudentUid),snap=await getDoc(ref);state=snap.exists()?normalize(snap.data()):normalize({classNo,studentNo});state.classNo=classNo;state.studentNo=studentNo;state.schedule=await loadCourse(classNo);selected=state.avatar;$('#studentAccess').classList.add('hide');if(!snap.exists()){$('#onboard').classList.remove('hide')}else{render();toast(`${state.name}, ?ㅼ떆 留뚮굹??諛섍??뚯슂`)}}catch(error){const code=error.code||'';if(create&&code.includes('email-already-in-use'))toast('?대? ?깅줉???숈깮?낅땲?? 濡쒓렇??踰꾪듉???뚮윭 二쇱꽭??');else if(!create&&(code.includes('invalid-credential')||code.includes('wrong-password')||code.includes('user-not-found')))toast('鍮꾨?踰덊샇媛 留욎? ?딄굅???깅줉?섏? ?딆? ?숈깮?낅땲??');else toast('濡쒓렇?명븯吏 紐삵뻽?듬땲?? ?좎떆 ???ㅼ떆 ?쒕룄??二쇱꽭??')}}
$('#studentLogin').onclick=()=>studentAccess(false);$('#studentCreate').onclick=()=>studentAccess(true);$('#loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')studentAccess(false)});
$('#start').onclick=()=>{const name=$('#name').value.trim();if(!name)return toast('?먰뿕媛 ?대쫫???곸뼱二쇱꽭??);state.name=name;state.avatar=selected;save();$('#onboard').classList.add('hide');render();toast('?먰뿕媛 怨꾩젙??留뚮뱾?댁죱?댁슂')};

function showTeacherAuth(action='panel'){teacherAction=action;$('#teacherPassword').value='';$('#teacherAuthCopy').textContent=action==='approve'?'15遺?嫄룰린瑜??뺤씤??援먯궗媛 ?몄쬆??二쇱꽭??':action.startsWith('reset')?'湲곕줉 珥덇린?붾? ?뱀씤??援먯궗媛 ?몄쬆??二쇱꽭??':'?대떦 諛섍낵 援먯궗??鍮꾨?踰덊샇瑜??낅젰?섏꽭??';if(state.classNo&&action!=='panel')$('#teacherClass').value=String(state.classNo);$('#teacherAuth').classList.remove('hide');setTimeout(()=>$('#teacherPassword').focus(),50)}
function resetFrom(index){state.entries=state.entries.slice(0,index);state.progress=index;state.steps=0;state.seen=-1;state.last='';state.walkSessions=Object.fromEntries(Object.entries(state.walkSessions||{}).filter(([key])=>Number(key)<index));state.teacherOverrides=Object.fromEntries(Object.entries(state.teacherOverrides||{}).filter(([key])=>Number(key)<index));walking=false;lastRenderedSteps=0;save();render()}
async function leaveTeacherMode(message='援먯궗紐⑤뱶媛 ?먮룞?쇰줈 爰쇱죱?듬땲??){teacherModeActive=false;teacherClass=null;await signOut(teacherAuth).catch(()=>{});$('#teacherPanel').classList.add('hide');render();if(message)toast(message)}
async function authenticateTeacher(){const classNo=Number($('#teacherClass').value),password=$('#teacherPassword').value;if(!password)return toast('援먯궗??鍮꾨?踰덊샇瑜??낅젰??二쇱꽭??);try{await signInWithEmailAndPassword(teacherAuth,teacherEmail(classNo),password);if(teacherAction!=='panel'&&Number(state.classNo)!==classNo){await signOut(teacherAuth);return toast('???숈깮???대떦 諛?援먯궗留??뱀씤?????덉뒿?덈떎.')}teacherClass=classNo;$('#teacherAuth').classList.add('hide');if(teacherAction==='approve'){state.teacherOverrides[state.progress]=true;save();await signOut(teacherAuth);openJournal(state.progress);toast('援먯궗 ?뺤씤???꾨즺?섏뿀?듬땲??)}else if(teacherAction==='resetAll'){let changed=false;if(confirm('???숈깮??紐⑤뱺 留덉쓬?쇱?? 吏꾪뻾?꾨? 珥덇린?뷀븷源뚯슂? ??젣??湲곕줉? 蹂듦뎄?????놁뒿?덈떎.')){resetFrom(0);changed=true}await leaveTeacherMode(changed?'紐⑤뱺 湲곕줉??珥덇린?붾릺怨?援먯궗紐⑤뱶媛 爰쇱죱?듬땲??:'援먯궗紐⑤뱶媛 爰쇱죱?듬땲??)}else if(teacherAction==='resetSelected'){const index=pendingResetIndex;let changed=false;if(Number.isInteger(index)&&confirm(`${index+1}李⑥떆遺???댄썑 湲곕줉怨?吏꾪뻾?꾨? 珥덇린?뷀븷源뚯슂? ??젣??湲곕줉? 蹂듦뎄?????놁뒿?덈떎.`)){resetFrom(index);changed=true}pendingResetIndex=null;await leaveTeacherMode(changed?`${index+1}李⑥떆遺??珥덇린?붾릺怨?援먯궗紐⑤뱶媛 爰쇱죱?듬땲??:'援먯궗紐⑤뱶媛 爰쇱죱?듬땲??)}else{teacherModeActive=true;$('#teacherPanelClass').textContent=`6?숇뀈 ${classNo}諛?;$('#teacherPanel').classList.remove('hide');$('#studentAccess').classList.add('hide');renderEntries();render()}}catch{toast('援먯궗??鍮꾨?踰덊샇媛 留욎? ?딆뒿?덈떎.')}}
function openResetChoice(){const completed=state.entries.map((entry,index)=>entry?{entry,index}:null).filter(Boolean);$('#resetLessonSelect').innerHTML=completed.length?completed.map(({entry,index})=>`<option value="${index}">${index+1}李⑥떆 쨌 ${escapeHtml(lessons[index][0])} 쨌 ${new Date(entry.date).toLocaleDateString('ko-KR')}</option>`).join(''):'<option value="">?꾨즺???깆같?쇱?媛 ?놁뒿?덈떎</option>';$('#resetSelected').disabled=!completed.length;$('#resetChoice').classList.remove('hide')}
$('#teacherEntry').onclick=()=>showTeacherAuth('panel');$('#closeTeacherAuth').onclick=()=>$('#teacherAuth').classList.add('hide');$('#enterTeacher').onclick=authenticateTeacher;$('#adminUnlock').onclick=()=>showTeacherAuth('approve');$('#resetJournals').onclick=openResetChoice;$('#closeResetChoice').onclick=()=>$('#resetChoice').classList.add('hide');$('#resetAll').onclick=()=>{$('#resetChoice').classList.add('hide');showTeacherAuth('resetAll')};$('#resetSelected').onclick=()=>{pendingResetIndex=Number($('#resetLessonSelect').value);$('#resetChoice').classList.add('hide');showTeacherAuth('resetSelected')};
const brand=$('.brand');['pointerdown','touchstart'].forEach(event=>brand.addEventListener(event,()=>{clearTimeout(pressTimer);pressTimer=setTimeout(()=>showTeacherAuth('panel'),5000)}));['pointerup','pointercancel','pointerleave','touchend'].forEach(event=>brand.addEventListener(event,()=>clearTimeout(pressTimer)));
$('#closeTeacherPanel').onclick=()=>$('#teacherPanel').classList.add('hide');
$('#turnOffTeacher').onclick=()=>leaveTeacherMode('援먯궗紐⑤뱶媛 爰쇱죱?듬땲??);
$('#teacherBadge').onclick=()=>{if(teacherModeActive){$('#teacherPanel').classList.remove('hide');renderEntries()}};
$('#teacherPreview').onclick=()=>{const i=state.progress;$('#checkNo').textContent=i+1;$('#checkTitle').textContent=lessons[i][0];$('#checkPrompt').textContent=lessons[i][1];$('#confirmCheckpoint').textContent='?대엺 留덉튂湲?;$('#checkpoint').classList.remove('hide')};
const normalConfirm=$('#confirmCheckpoint').onclick;$('#confirmCheckpoint').onclick=()=>{if($('#confirmCheckpoint').textContent==='?대엺 留덉튂湲?)return $('#checkpoint').classList.add('hide');normalConfirm()};

let passwordResetTarget=null;
function openPasswordReset(uid,classNo,studentNo,name){passwordResetTarget={uid,classNo,studentNo,name};$('#passwordResetStudent').textContent=`6?숇뀈 ${classNo}諛?${studentNo}踰?쨌 ${name||'?대쫫 誘몄꽕??} ?숈깮????鍮꾨?踰덊샇瑜??뺥빀?덈떎.`;$('#newStudentPassword').value='';$('#confirmStudentPassword').value='';$('#passwordReset').classList.remove('hide');setTimeout(()=>$('#newStudentPassword').focus(),50)}
$('#closePasswordReset').onclick=()=>{$('#passwordReset').classList.add('hide');passwordResetTarget=null};
$('#submitPasswordReset').onclick=async()=>{const password=$('#newStudentPassword').value,confirmPassword=$('#confirmStudentPassword').value;if(!passwordResetTarget)return;if(password.length<6)return toast('??鍮꾨?踰덊샇瑜?6???댁긽 ?낅젰??二쇱꽭??);if(password!==confirmPassword)return toast('??鍮꾨?踰덊샇媛 ?쒕줈 ?ㅻ쫭?덈떎');const button=$('#submitPasswordReset');button.disabled=true;button.textContent='珥덇린?뷀븯??以묅?;try{const token=await teacherAuth.currentUser?.getIdToken();if(!token)throw new Error('援먯궗 ?몄쬆??留뚮즺?섏뿀?듬땲??);const response=await fetch('/api/reset-student-password',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({studentUid:passwordResetTarget.uid,newPassword:password})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||'鍮꾨?踰덊샇瑜?珥덇린?뷀븯吏 紐삵뻽?듬땲??);$('#passwordReset').classList.add('hide');passwordResetTarget=null;toast('?숈깮 鍮꾨?踰덊샇媛 珥덇린?붾릺?덉뒿?덈떎')}catch(error){toast(error.message||'鍮꾨?踰덊샇瑜?珥덇린?뷀븯吏 紐삵뻽?듬땲??)}finally{button.disabled=false;button.textContent='鍮꾨?踰덊샇 珥덇린??}};
async function renderEntries(){if(!teacherClass)return;$('#teacherContent').innerHTML='<div class="empty">?숈깮 湲곕줉??遺덈윭?ㅻ뒗 以묒엯?덈떎.</div>';try{const snap=await getDocs(query(collection(teacherDb,'students'),where('classNo','==',teacherClass)));const students=snap.docs.map(d=>({uid:d.id,...d.data()})).sort((a,b)=>(a.studentNo||0)-(b.studentNo||0));$('#teacherContent').innerHTML=students.length?students.map(s=>`<section class="entry-card" style="margin-top:12px"><header><strong>6?숇뀈 ${s.classNo}諛?${s.studentNo}踰?쨌 ${escapeHtml(s.name||'?대쫫 誘몄꽕??)} ${escapeHtml(s.avatar||'')}</strong><span>${s.progress||0}/15 ?꾨즺</span></header><button class="btn secondary student-password-reset" style="padding:7px 10px;margin:0 0 10px" data-uid="${escapeHtml(s.uid)}" data-class="${s.classNo}" data-number="${s.studentNo}" data-name="${escapeHtml(s.name||'')}">鍮꾨?踰덊샇 珥덇린??/button>${(s.entries||[]).map((e,i)=>e?`<details style="padding:8px 0;border-top:1px solid #e2e3dd"><summary>${i+1}李⑥떆 쨌 ${escapeHtml(lessons[i][0])} 쨌 ${new Date(e.date).toLocaleDateString('ko-KR')}</summary><p style="margin-top:10px">${escapeHtml(e.text)}</p></details>`:'').join('')||'<p style="color:#777">?꾩쭅 ?묒꽦???깆같?쇱?媛 ?놁뒿?덈떎.</p>'}</section>`).join(''):'<div class="empty">??諛섏뿉 ?깅줉???숈깮???놁뒿?덈떎.</div>';document.querySelectorAll('.student-password-reset').forEach(button=>button.onclick=()=>openPasswordReset(button.dataset.uid,Number(button.dataset.class),Number(button.dataset.number),button.dataset.name));$('#tabEntries').className='btn';$('#tabSchedule').className='btn secondary'}catch{$('#teacherContent').innerHTML='<div class="empty">?숈깮 湲곕줉??遺덈윭?ㅼ? 紐삵뻽?듬땲?? Firestore 洹쒖튃???뺤씤??二쇱꽭??</div>'}}
async function renderSchedule(){const schedule=await loadCourse(teacherClass,teacherDb);$('#teacherContent').innerHTML=`<div class="schedule-list">${lessons.map((l,i)=>`<label class="schedule-row"><b>${i+1}李⑥떆</b><span><strong style="display:block;margin-bottom:5px">${escapeHtml(l[0])}</strong><small style="display:block;color:#666d66;line-height:1.5">${escapeHtml(l[1])}</small></span><input type="date" aria-label="${i+1}李⑥떆 怨듦컻 ?좎쭨" data-date="${i}" value="${schedule[i]}"></label>`).join('')}</div>`;document.querySelectorAll('[data-date]').forEach(input=>input.onchange=async()=>{schedule[Number(input.dataset.date)]=input.value;await setDoc(doc(teacherDb,'course',`class-${teacherClass}`),{classNo:teacherClass,schedule,updatedAt:new Date().toISOString()},{merge:true});if(Number(state.classNo)===teacherClass){state.schedule=schedule;save();render()}toast('怨듦컻 ?좎쭨媛 ??λ릺?덉뒿?덈떎')});$('#tabEntries').className='btn secondary';$('#tabSchedule').className='btn'}
$('#tabEntries').onclick=renderEntries;$('#tabSchedule').onclick=renderSchedule;

await signOut(auth).catch(()=>{});await signOut(teacherAuth).catch(()=>{});state=freshState();render();startClock();

